title: Brunner's Feinklang

tabs:
  overview:
    label: "Übersicht"
    icon: globe
    sections:
      all_pages:
        type: pages
        label: "Alle Seiten"
        layout: list
        image:
          query: false
          back: black

  navigation:
    icon: menu
    label: "Navigation"
    sections:
      main_nav:
        type: pages
        status: listed
        label: "Hauptnavigation"
        image: false
      footer_nav:
        type: fields
        fields:
          tw_footer_nav:
            type: pages
            label: Navigation im Footer
            image: false
  meta:
    icon: info
    label: "Meta-Informationen"
    columns:
      left:
        width: 2/3
        sections:
          meta_info:
            type: fields
            fields:
              ch_meta_headline:
                label: "Plattformübergreifend"
                type: headline
              ch_meta_title:
                label: "Title"
                type: text
                width: 1/2
              ch_meta_url:
                label: "URL"
                type: url
                width: 1/2
              ch_meta_description:
                type: textarea
                label: "Beschreibung"
              ch_og_headline:
                label: "Open Graph"
                type: headline
              ch_og_type:
                label: Open Graph Type
                type: text
              ch_twitter_headline:
                label: "X / chitter"
                type: headline
              ch_twitter_card:
                label: "Twitter Card"
                type: text
                width: 1/3
              ch_twitter_site:
                label: "Twitter Site"
                type: text
                width: 1/3
              ch_twitter_creator:
                label: "Twitter Creator"
                type: text
                width: 1/3
      right:
        width: 1/3
        sections:
          graphics:
            type: fields
            fields:
              ch_images_headline:
                label: "Images"
                type: headline
              ch_og_image:
                label: "Open Graph Image"
                type: files
                multiple: false
              ch_twitter_image:
                label: "Twitter Image"
                type: files
                multiple: false
